version: '3.9'
services:
  server:
    container_name: server
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./server:/app
  client:
    container_name: client
    platform: linux/amd64
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
